name: flutterfordev
description: Flutter For Dev - Web version.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 

  cupertino_icons: ^1.0.5
  transparent_image: ^2.0.0 
  json_annotation: ^4.0.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5
  dio: ^4.0.0
  flutter_lints: ^2.0.1
  analyzer: ^4.6.0
  

dev_dependencies:
  test: 
  json_serializable: 
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
     

flutter:

  uses-material-design: true

  assets:
    - assets/images/image_main.jpg
    - assets/images/image_main.png

  fonts:
    - family: Fixedsys
      fonts:
        - asset: assets/fonts/Fixedsys.ttf
