// class Autogenerated {
//   String status;
//   Response response;

//   Autogenerated({this.status, this.response});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     response = json['response'] != null
//         ? new Response.fromJson(json['response'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     if (this.response != null) {
//       data['response'] = this.response.toJson();
//     }
//     return data;
//   }
// }

// class Response {
//   int id;
//   String title;
//   String username;
//   int participantsCount;
//   int avgPostReach;
//   double errPercent;
//   int dailyReach;
//   double ciIndex;

//   Response(
//       {this.id,
//       this.title,
//       this.username,
//       this.participantsCount,
//       this.avgPostReach,
//       this.errPercent,
//       this.dailyReach,
//       this.ciIndex});

//   Response.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     username = json['username'];
//     participantsCount = json['participants_count'];
//     avgPostReach = json['avg_post_reach'];
//     errPercent = json['err_percent'];
//     dailyReach = json['daily_reach'];
//     ciIndex = json['ci_index'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['username'] = this.username;
//     data['participants_count'] = this.participantsCount;
//     data['avg_post_reach'] = this.avgPostReach;
//     data['err_percent'] = this.errPercent;
//     data['daily_reach'] = this.dailyReach;
//     data['ci_index'] = this.ciIndex;
//     return data;
//   }
// }
